// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckPath(arg1:string):Promise<models.FileLink>;

export function DeleteAllProjects():Promise<number>;

export function DeleteProject(arg1:string):Promise<boolean>;

export function GetProjects():Promise<Array<models.Project>>;

export function OpenFile(arg1:string):Promise<void>;

export function SaveProject(arg1:models.Project):Promise<models.Project>;

export function SelectFiles():Promise<Array<models.FileLink>>;

export function SelectFolder():Promise<Array<models.FileLink>>;

export function UpdateProjects(arg1:Array<models.Project>):Promise<boolean>;
