// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteAllProjects():Promise<number>;

export function DeleteProject(arg1:string):Promise<boolean>;

export function GetProjects():Promise<Array<main.Project>>;

export function Greet(arg1:string):Promise<string>;

export function SaveProject(arg1:main.Project):Promise<main.Project>;
